import type { Metadata } from "next";
import "./globals.css";
import React from 'react';
import { ApolloWrapper } from '@/app/apollo-wrapper';

export const metadata: Metadata = {
  title: "Subscriptions Demo - Don't forget to like and subscribe",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-sky-500">
        <ApolloWrapper>{children}</ApolloWrapper>
      </body>
    </html>
  );
}
